{
 "title": "Ancillary Services",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Basic Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Number of cores being utilised",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Activity (Bytes Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Network Activity (Bytes transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Disk write operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk write traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk read operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk read traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{container_label_com_docker_compose_service=~\"(cadvisor)|(docker-socket-proxy)|(grafana)|(postgres-exporter)|(prometheus)|(alloy)|(loki)\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}