{
 "title": "Web (Lightning)",
 "description": "Charts relating to the performance of Lightning, the associated worker and PostgreSQL instance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Basic Stats",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container_label_com_docker_compose_service=~\"lightning|postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Number of cores being utilised",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory ",
   "type": "timeseries",
   "description": "Memory used by container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"lightning\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Activity (Bytes Received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Network Activity (Bytes Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Disk write operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk write traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk read operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk read traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{container_label_com_docker_compose_service=\"lightning\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Postgresql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Percentage of available CPU utilised",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"postgres\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Activity (Bytes Received)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "{{name}}-{{interface}}"
      }
     ]
    },
    {
     "title": "Network Activity (Bytes Transmitted)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "{{name}}-{{interface}}"
      }
     ]
    },
    {
     "title": "Disk write operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk write traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk read operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk read traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{container_label_com_docker_compose_service=\"postgres\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Connection Utilisation",
     "type": "timeseries",
     "description": "Fraction of the max connection limit that is currently utilised.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum (pg_stat_database_numbackends{job=\"postgres\"})/sum (pg_settings_max_connections{job=\"postgres\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "HTTP requests as reported by Phoenix",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(lightning_prom_ex_phoenix_http_requests_total{job=\"lightning\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Data Transfer Size",
   "type": "timeseries",
   "description": "Amount of data transferred via HTTP for all pods servicing `openfn.palladiumethiopia.com`",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(lightning_prom_ex_phoenix_http_response_size_bytes_sum{job=\"lightning\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Error Percentage",
   "type": "timeseries",
   "description": "Percentage of HTTP requests that returned a status of 4xx or 5xx.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(lightning_prom_ex_phoenix_http_requests_total{job=\"lightning\", status=~\"(4|5)..\"}[$__rate_interval]))\n/\nsum by(instance) (rate(lightning_prom_ex_phoenix_http_requests_total{job=\"lightning\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average time per SQL query",
   "type": "timeseries",
   "description": "Average time spent per SQL query",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(lightning_prom_ex_ecto_repo_query_total_time_milliseconds_sum{job=\"lightning\"}[$__rate_interval]))\n/ on(instance)\nsum by(instance) (rate(lightning_prom_ex_ecto_repo_query_total_time_milliseconds_count{job=\"lightning\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Websocket Channel Events",
   "type": "timeseries",
   "description": "Rate of Websocket events across all channels",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Average Run Claim TIme",
   "type": "timeseries",
   "description": "Average time taken for a worker to claim a run",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(lightning_run_queue_claim_average_duration_milliseconds{job=\"lightning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs Available",
   "type": "timeseries",
   "description": "Runs that can be claimed by the worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "avg(lightning_run_queue_available_count{job=\"lightning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Run Queue Delay",
   "type": "heatmap",
   "description": "A distribution of the time spent by a run in the queue before it is claimed by a worker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_run_queue_delay_milliseconds_bucket{job=\"lightning\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs finalised",
   "type": "timeseries",
   "description": "The number of runs that reach a final state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "avg(lightning_run_queue_finalised_count{job=\"lightning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Worker Websocket Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Average claim event times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"lightning\", event=\"claim\"}[$__rate_interval]) / irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\", event=\"claim\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "claim event distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"lightning\", event=\"claim\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fetch:credential event duration",
   "type": "timeseries",
   "description": "Average duration of the `fetch:credential` event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"lightning\", event=\"fetch:credential\"}[$__rate_interval]) / irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\", event=\"fetch:credential\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fetch:credential event distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"lightning\", event=\"fetch:credential\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "run:start event duration",
   "type": "timeseries",
   "description": "Average duration of the `run:start` event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"lightning\", event=\"run:start\"}[$__rate_interval]) / irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\", event=\"run:start\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "run:start event distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"lightning\", event=\"run:start\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "run:log event duration",
   "type": "timeseries",
   "description": "Average duration of the `run:log` event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"lightning\", event=\"run:log\"}[$__rate_interval]) / irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\", event=\"run:log\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "run:log event distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"lightning\", event=\"run:log\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "step:complete event duration",
   "type": "timeseries",
   "description": "Average duration of the `step:complete` event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"lightning\", event=\"step:complete\"}[$__rate_interval]) / irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\", event=\"step:complete\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "step:complete event distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"lightning\", event=\"step:complete\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "run:complete event duration",
   "type": "timeseries",
   "description": "Average duration of the `run:complete` event.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"lightning\", event=\"run:complete\"}[$__rate_interval]) / irate(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"lightning\", event=\"run:complete\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "run:complete event distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "sum by(le) (increase(lightning_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"lightning\", event=\"run:complete\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}