{
 "title": "Worker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Basic Stats",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container_label_com_docker_compose_service=\"worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Number of cores being utilised",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Memory usage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"worker\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Activity (Bytes Received)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}-{{interface}}"
      }
     ]
    },
    {
     "title": "Network Activity (Bytes transmitted)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}-{{interface}}"
      }
     ]
    },
    {
     "title": "Disk write operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk write traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk read operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk read traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{container_label_com_docker_compose_service=\"worker\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lost Runs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lightning_run_lost_count{job=\"lightning\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Claim Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "direction": "backward",
       "expr": "rate({service_name=\"/v01-worker-1\"} |= \"TIMEOUT on claim\" [$__auto])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Connection to Lightning lost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "direction": "backward",
       "expr": "rate({service_name=\"/v01-worker-1\"} |= \"Connection to lightning lost\" [$__auto])",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Connection timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "direction": "backward",
       "expr": "rate({service_name=\"/v01-worker-1\"} |~ \"ERR:.+timeout$\" [$__auto])",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}